/**
 * NorthPlate — Vehicle Data Module
 * Data sourced from NRCan 2026 Fuel Consumption Guide (seed.csv)
 * Supplemented with additional popular Canadian models
 */

'use strict';

const NorthPlateData = (() => {

  const RAW_VEHICLES = [
    // --- From NRCan 2026 Fuel Consumption Guide (seed.csv) ---
    { id:1,  make:'Honda',      model:'Civic Sedan',        year:2026, trim:'Base',              class:'Compact Car',      body_style:'Car',   engine_litres:2.0, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'FWD', fuel_type:'gasoline', fuel_city_l100km:7.4,  fuel_hwy_l100km:5.8,  fuel_combined_l100km:6.7,  ev_range_km:null, ev_range_cold_km:null, co2_rating:6,  smog_rating:6,  msrp_cad:26700,  ground_clearance_mm:127 },
    { id:2,  make:'Honda',      model:'Civic Sedan Hybrid', year:2026, trim:'Base',              class:'Compact Car',      body_style:'Car',   engine_litres:2.0, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'FWD', fuel_type:'hybrid',   fuel_city_l100km:4.7,  fuel_hwy_l100km:5.1,  fuel_combined_l100km:4.9,  ev_range_km:null, ev_range_cold_km:null, co2_rating:8,  smog_rating:6,  msrp_cad:34990,  ground_clearance_mm:127 },
    { id:3,  make:'Toyota',     model:'Corolla Hybrid',     year:2026, trim:'AWD',               class:'Compact Car',      body_style:'Car',   engine_litres:1.8, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'AWD', fuel_type:'hybrid',   fuel_city_l100km:4.6,  fuel_hwy_l100km:5.3,  fuel_combined_l100km:4.9,  ev_range_km:null, ev_range_cold_km:null, co2_rating:8,  smog_rating:6,  msrp_cad:28400,  ground_clearance_mm:132 },
    { id:4,  make:'Toyota',     model:'Prius',              year:2026, trim:'AWD',               class:'Compact Car',      body_style:'Car',   engine_litres:2.0, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'AWD', fuel_type:'hybrid',   fuel_city_l100km:4.8,  fuel_hwy_l100km:4.7,  fuel_combined_l100km:4.8,  ev_range_km:null, ev_range_cold_km:null, co2_rating:8,  smog_rating:6,  msrp_cad:37990,  ground_clearance_mm:142 },
    { id:5,  make:'Toyota',     model:'Camry',              year:2026, trim:'Hybrid',            class:'Mid-size Car',     body_style:'Car',   engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'FWD', fuel_type:'hybrid',   fuel_city_l100km:5.0,  fuel_hwy_l100km:5.0,  fuel_combined_l100km:5.0,  ev_range_km:null, ev_range_cold_km:null, co2_rating:8,  smog_rating:7,  msrp_cad:35290,  ground_clearance_mm:140 },
    { id:6,  make:'Hyundai',    model:'Elantra Hybrid',     year:2026, trim:'Base',              class:'Compact Car',      body_style:'Car',   engine_litres:1.6, cylinders:4, motor_kw:null, transmission:'DCT',          drivetrain:'FWD', fuel_type:'hybrid',   fuel_city_l100km:4.8,  fuel_hwy_l100km:4.5,  fuel_combined_l100km:4.7,  ev_range_km:null, ev_range_cold_km:null, co2_rating:8,  smog_rating:6,  msrp_cad:28699,  ground_clearance_mm:140 },
    { id:7,  make:'Hyundai',    model:'Sonata Hybrid',      year:2026, trim:'Base',              class:'Mid-size Car',     body_style:'Car',   engine_litres:2.0, cylinders:4, motor_kw:null, transmission:'DCT',          drivetrain:'FWD', fuel_type:'hybrid',   fuel_city_l100km:5.3,  fuel_hwy_l100km:4.6,  fuel_combined_l100km:5.0,  ev_range_km:null, ev_range_cold_km:null, co2_rating:8,  smog_rating:6,  msrp_cad:37399,  ground_clearance_mm:140 },
    { id:8,  make:'Toyota',     model:'RAV4 Hybrid',        year:2026, trim:'AWD XLE',           class:'Compact SUV',      body_style:'SUV',   engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'AWD', fuel_type:'hybrid',   fuel_city_l100km:5.2,  fuel_hwy_l100km:6.1,  fuel_combined_l100km:5.7,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:6,  msrp_cad:43450,  ground_clearance_mm:189 },
    { id:9,  make:'Honda',      model:'CR-V Hybrid',        year:2026, trim:'AWD',               class:'Compact SUV',      body_style:'SUV',   engine_litres:2.0, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'AWD', fuel_type:'hybrid',   fuel_city_l100km:6.0,  fuel_hwy_l100km:6.9,  fuel_combined_l100km:6.4,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:7,  msrp_cad:44790,  ground_clearance_mm:204 },
    { id:10, make:'Ford',       model:'Escape Hybrid',      year:2026, trim:'AWD',               class:'Compact SUV',      body_style:'SUV',   engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'AWD', fuel_type:'hybrid',   fuel_city_l100km:5.6,  fuel_hwy_l100km:6.5,  fuel_combined_l100km:6.0,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:7,  msrp_cad:38990,  ground_clearance_mm:192 },
    { id:11, make:'Hyundai',    model:'Santa Fe Hybrid',    year:2026, trim:'AWD',               class:'Mid-size SUV',     body_style:'SUV',   engine_litres:1.6, cylinders:4, motor_kw:null, transmission:'DCT',          drivetrain:'AWD', fuel_type:'hybrid',   fuel_city_l100km:6.9,  fuel_hwy_l100km:7.0,  fuel_combined_l100km:6.9,  ev_range_km:null, ev_range_cold_km:null, co2_rating:6,  smog_rating:6,  msrp_cad:44999,  ground_clearance_mm:196 },
    { id:12, make:'Chevrolet',  model:'Equinox',            year:2026, trim:'AWD',               class:'Compact SUV',      body_style:'SUV',   engine_litres:1.5, cylinders:4, motor_kw:null, transmission:'8-spd Auto',   drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:9.6,  fuel_hwy_l100km:8.1,  fuel_combined_l100km:8.9,  ev_range_km:null, ev_range_cold_km:null, co2_rating:5,  smog_rating:6,  msrp_cad:39898,  ground_clearance_mm:190 },
    { id:13, make:'BMW',        model:'X3',                 year:2026, trim:'30 xDrive',         class:'Compact SUV',      body_style:'SUV',   engine_litres:2.0, cylinders:4, motor_kw:null, transmission:'8-spd Auto',   drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:8.8,  fuel_hwy_l100km:7.1,  fuel_combined_l100km:8.1,  ev_range_km:null, ev_range_cold_km:null, co2_rating:6,  smog_rating:7,  msrp_cad:56900,  ground_clearance_mm:204 },
    { id:14, make:'Ford',       model:'Escape PHEV',        year:2026, trim:'AWD',               class:'Compact SUV',      body_style:'SUV',   engine_litres:2.5, cylinders:4, motor_kw:85,   transmission:'CVT',          drivetrain:'AWD', fuel_type:'PHEV',     fuel_city_l100km:5.6,  fuel_hwy_l100km:6.3,  fuel_combined_l100km:5.9,  ev_range_km:60,  ev_range_cold_km:36,  co2_rating:9,  smog_rating:7,  msrp_cad:44490,  ground_clearance_mm:192 },
    { id:15, make:'Hyundai',    model:'Tucson PHEV',        year:2026, trim:'AWD',               class:'Compact SUV',      body_style:'SUV',   engine_litres:1.6, cylinders:4, motor_kw:66,   transmission:'DCT',          drivetrain:'AWD', fuel_type:'PHEV',     fuel_city_l100km:6.7,  fuel_hwy_l100km:6.8,  fuel_combined_l100km:6.7,  ev_range_km:51,  ev_range_cold_km:31,  co2_rating:9,  smog_rating:6,  msrp_cad:52099,  ground_clearance_mm:181 },
    { id:16, make:'Mitsubishi', model:'Outlander PHEV',     year:2026, trim:'AWD',               class:'Mid-size SUV',     body_style:'SUV',   engine_litres:2.4, cylinders:4, motor_kw:60,   transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'PHEV',     fuel_city_l100km:8.6,  fuel_hwy_l100km:8.6,  fuel_combined_l100km:8.6,  ev_range_km:72,  ev_range_cold_km:43,  co2_rating:9,  smog_rating:6,  msrp_cad:50498,  ground_clearance_mm:200 },
    { id:17, make:'Volvo',      model:'XC60 T8',            year:2026, trim:'AWD Recharge',      class:'Compact SUV',      body_style:'SUV',   engine_litres:2.0, cylinders:4, motor_kw:107,  transmission:'8-spd Auto',   drivetrain:'AWD', fuel_type:'PHEV',     fuel_city_l100km:8.5,  fuel_hwy_l100km:8.5,  fuel_combined_l100km:8.5,  ev_range_km:58,  ev_range_cold_km:35,  co2_rating:9,  smog_rating:6,  msrp_cad:82500,  ground_clearance_mm:201 },
    { id:18, make:'Ford',       model:'F-150',              year:2026, trim:'4X4 2.7L EcoBoost', class:'Full-size Pickup', body_style:'Truck', engine_litres:2.7, cylinders:6, motor_kw:null, transmission:'10-spd Auto',  drivetrain:'4WD', fuel_type:'gasoline', fuel_city_l100km:13.1, fuel_hwy_l100km:10.2, fuel_combined_l100km:11.8, ev_range_km:null, ev_range_cold_km:null, co2_rating:4,  smog_rating:5,  msrp_cad:56900,  ground_clearance_mm:226 },
    { id:19, make:'Ford',       model:'F-150 Hybrid',       year:2026, trim:'4X4 PowerBoost',    class:'Full-size Pickup', body_style:'Truck', engine_litres:3.5, cylinders:6, motor_kw:null, transmission:'10-spd Auto',  drivetrain:'4WD', fuel_type:'hybrid',   fuel_city_l100km:11.3, fuel_hwy_l100km:10.0, fuel_combined_l100km:10.7, ev_range_km:null, ev_range_cold_km:null, co2_rating:4,  smog_rating:5,  msrp_cad:63900,  ground_clearance_mm:226 },
    { id:20, make:'Chevrolet',  model:'Silverado 4WD',      year:2026, trim:'3.0L Duramax Diesel',class:'Full-size Pickup',body_style:'Truck', engine_litres:3.0, cylinders:6, motor_kw:null, transmission:'10-spd Auto',  drivetrain:'4WD', fuel_type:'diesel',   fuel_city_l100km:10.7, fuel_hwy_l100km:9.3,  fuel_combined_l100km:10.1, ev_range_km:null, ev_range_cold_km:null, co2_rating:4,  smog_rating:4,  msrp_cad:60795,  ground_clearance_mm:224 },
    { id:21, make:'Toyota',     model:'Tacoma Hybrid',      year:2026, trim:'4WD Limited',       class:'Mid-size Pickup',  body_style:'Truck', engine_litres:2.4, cylinders:4, motor_kw:null, transmission:'8-spd Auto',   drivetrain:'4WD', fuel_type:'hybrid',   fuel_city_l100km:10.5, fuel_hwy_l100km:9.7,  fuel_combined_l100km:10.1, ev_range_km:null, ev_range_cold_km:null, co2_rating:5,  smog_rating:6,  msrp_cad:57300,  ground_clearance_mm:235 },
    { id:22, make:'Toyota',     model:'Tundra Hybrid',      year:2026, trim:'4WD',               class:'Full-size Pickup', body_style:'Truck', engine_litres:3.4, cylinders:6, motor_kw:null, transmission:'10-spd Auto',  drivetrain:'4WD', fuel_type:'hybrid',   fuel_city_l100km:12.7, fuel_hwy_l100km:10.5, fuel_combined_l100km:11.7, ev_range_km:null, ev_range_cold_km:null, co2_rating:4,  smog_rating:4,  msrp_cad:64800,  ground_clearance_mm:254 },
    { id:23, make:'Tesla',      model:'Model Y',            year:2026, trim:'Long Range AWD',    class:'Mid-size SUV',     body_style:'SUV',   engine_litres:null,cylinders:0, motor_kw:378,  transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:542, ev_range_cold_km:325, co2_rating:10, smog_rating:10, msrp_cad:74990,  ground_clearance_mm:167, kwh_per_100km:17.3 },
    { id:24, make:'Tesla',      model:'Model 3',            year:2026, trim:'Performance AWD',   class:'Mid-size Car',     body_style:'Car',   engine_litres:null,cylinders:0, motor_kw:358,  transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:497, ev_range_cold_km:298, co2_rating:10, smog_rating:10, msrp_cad:79990,  ground_clearance_mm:140, kwh_per_100km:18.4 },
    { id:25, make:'Hyundai',    model:'IONIQ 5',            year:2026, trim:'Long Range RWD',    class:'Mid-size SUV',     body_style:'SUV',   engine_litres:null,cylinders:0, motor_kw:160,  transmission:'1-spd Auto',   drivetrain:'RWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:504, ev_range_cold_km:302, co2_rating:10, smog_rating:10, msrp_cad:60999,  ground_clearance_mm:178, kwh_per_100km:16.9 },
    { id:26, make:'Chevrolet',  model:'Equinox EV',         year:2026, trim:'AWD',               class:'Compact SUV',      body_style:'SUV',   engine_litres:null,cylinders:0, motor_kw:215,  transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:494, ev_range_cold_km:296, co2_rating:10, smog_rating:10, msrp_cad:54898,  ground_clearance_mm:190, kwh_per_100km:20.3 },
    { id:27, make:'Volkswagen', model:'ID.4',               year:2026, trim:'AWD Pro S',         class:'Mid-size SUV',     body_style:'SUV',   engine_litres:null,cylinders:0, motor_kw:210,  transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:423, ev_range_cold_km:254, co2_rating:10, smog_rating:10, msrp_cad:62995,  ground_clearance_mm:180, kwh_per_100km:20.5 },
    { id:28, make:'Kia',        model:'EV9',                year:2026, trim:'Wind RWD',          class:'Mid-size SUV',     body_style:'SUV',   engine_litres:null,cylinders:0, motor_kw:160,  transmission:'1-spd Auto',   drivetrain:'RWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:491, ev_range_cold_km:295, co2_rating:10, smog_rating:10, msrp_cad:72995,  ground_clearance_mm:199, kwh_per_100km:23.6 },
    { id:29, make:'Nissan',     model:'LEAF',               year:2026, trim:'SV Plus',           class:'Compact Car',      body_style:'Car',   engine_litres:null,cylinders:0, motor_kw:160,  transmission:'1-spd Auto',   drivetrain:'FWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:463, ev_range_cold_km:278, co2_rating:10, smog_rating:10, msrp_cad:41498,  ground_clearance_mm:155, kwh_per_100km:18.4 },
    { id:30, make:'Toyota',     model:'bZ4X',               year:2026, trim:'AWD',               class:'Compact SUV',      body_style:'SUV',   engine_litres:null,cylinders:0, motor_kw:160,  transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:468, ev_range_cold_km:281, co2_rating:10, smog_rating:10, msrp_cad:55990,  ground_clearance_mm:177, kwh_per_100km:17.3 },

    // --- Supplemental popular Canadian models ---
    { id:31, make:'Toyota',     model:'RAV4',               year:2026, trim:'XLE AWD',           class:'Compact SUV',      body_style:'SUV',   engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'8-spd Auto',   drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:9.5,  fuel_hwy_l100km:7.4,  fuel_combined_l100km:8.6,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:5,  msrp_cad:36950,  ground_clearance_mm:189 },
    { id:32, make:'Honda',      model:'CR-V',               year:2026, trim:'LX AWD',            class:'Compact SUV',      body_style:'SUV',   engine_litres:1.5, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:9.7,  fuel_hwy_l100km:8.0,  fuel_combined_l100km:8.9,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:5,  msrp_cad:38590,  ground_clearance_mm:204 },
    { id:33, make:'Mazda',      model:'CX-5',               year:2026, trim:'GX AWD',            class:'Compact SUV',      body_style:'SUV',   engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'6-spd Auto',   drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:9.7,  fuel_hwy_l100km:8.4,  fuel_combined_l100km:9.1,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:5,  msrp_cad:34450,  ground_clearance_mm:213 },
    { id:34, make:'Nissan',     model:'Rogue',              year:2026, trim:'S AWD',             class:'Compact SUV',      body_style:'SUV',   engine_litres:1.5, cylinders:3, motor_kw:null, transmission:'CVT',          drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:8.8,  fuel_hwy_l100km:7.6,  fuel_combined_l100km:8.3,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:5,  msrp_cad:33898,  ground_clearance_mm:210 },
    { id:35, make:'Subaru',     model:'Outback',            year:2026, trim:'Touring XT AWD',    class:'Mid-size SUV',     body_style:'SUV',   engine_litres:2.4, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:9.8,  fuel_hwy_l100km:8.5,  fuel_combined_l100km:9.2,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:5,  msrp_cad:47795,  ground_clearance_mm:213 },
    { id:36, make:'Subaru',     model:'Forester',           year:2026, trim:'Premier AWD',       class:'Compact SUV',      body_style:'SUV',   engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:9.8,  fuel_hwy_l100km:8.7,  fuel_combined_l100km:9.3,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:5,  msrp_cad:40495,  ground_clearance_mm:220 },
    { id:37, make:'Kia',        model:'Sportage',           year:2026, trim:'LX AWD',            class:'Compact SUV',      body_style:'SUV',   engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'8-spd Auto',   drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:10.0, fuel_hwy_l100km:8.2,  fuel_combined_l100km:9.2,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:3,  msrp_cad:33995,  ground_clearance_mm:181 },
    { id:38, make:'Mazda',      model:'CX-50',              year:2026, trim:'GS AWD',            class:'Compact SUV',      body_style:'SUV',   engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'6-spd Auto',   drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:10.2, fuel_hwy_l100km:8.6,  fuel_combined_l100km:9.5,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:3,  msrp_cad:39050,  ground_clearance_mm:224 },
    { id:39, make:'Hyundai',    model:'Tucson',             year:2026, trim:'Preferred AWD',     class:'Compact SUV',      body_style:'SUV',   engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'8-spd Auto',   drivetrain:'AWD', fuel_type:'gasoline', fuel_city_l100km:10.2, fuel_hwy_l100km:8.2,  fuel_combined_l100km:9.3,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:3,  msrp_cad:37999,  ground_clearance_mm:181 },
    { id:40, make:'Toyota',     model:'4Runner',            year:2026, trim:'TRD Off-Road 4WD',  class:'Mid-size SUV',     body_style:'SUV',   engine_litres:2.4, cylinders:4, motor_kw:null, transmission:'8-spd Auto',   drivetrain:'4WD', fuel_type:'gasoline', fuel_city_l100km:12.4, fuel_hwy_l100km:10.3, fuel_combined_l100km:11.5, ev_range_km:null, ev_range_cold_km:null, co2_rating:6,  smog_rating:3,  msrp_cad:62650,  ground_clearance_mm:224 },
    { id:41, make:'Ram',        model:'1500',               year:2026, trim:'Classic SLT 4x4',   class:'Full-size Pickup', body_style:'Truck', engine_litres:5.7, cylinders:8, motor_kw:null, transmission:'8-spd Auto',   drivetrain:'4WD', fuel_type:'gasoline', fuel_city_l100km:16.1, fuel_hwy_l100km:12.0, fuel_combined_l100km:14.3, ev_range_km:null, ev_range_cold_km:null, co2_rating:6,  smog_rating:3,  msrp_cad:59595,  ground_clearance_mm:224 },
    { id:42, make:'GMC',        model:'Sierra 1500',        year:2026, trim:'AT4 4WD',           class:'Full-size Pickup', body_style:'Truck', engine_litres:6.2, cylinders:8, motor_kw:null, transmission:'10-spd Auto',  drivetrain:'4WD', fuel_type:'gasoline', fuel_city_l100km:15.7, fuel_hwy_l100km:11.2, fuel_combined_l100km:13.7, ev_range_km:null, ev_range_cold_km:null, co2_rating:6,  smog_rating:3,  msrp_cad:70195,  ground_clearance_mm:249 },
    { id:43, make:'Kia',        model:'Sportage Hybrid',    year:2026, trim:'EX AWD',            class:'Compact SUV',      body_style:'SUV',   engine_litres:1.6, cylinders:4, motor_kw:66,   transmission:'6-spd Auto',   drivetrain:'AWD', fuel_type:'hybrid',   fuel_city_l100km:6.8,  fuel_hwy_l100km:7.4,  fuel_combined_l100km:7.1,  ev_range_km:null, ev_range_cold_km:null, co2_rating:7,  smog_rating:5,  msrp_cad:44595,  ground_clearance_mm:181 },
    { id:44, make:'Hyundai',    model:'IONIQ 6',            year:2026, trim:'Long Range AWD',    class:'Mid-size Car',     body_style:'Car',   engine_litres:null,cylinders:0, motor_kw:239,  transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:581, ev_range_cold_km:349, co2_rating:10, smog_rating:10, msrp_cad:64999,  ground_clearance_mm:145, kwh_per_100km:14.9 },
    { id:45, make:'Kia',        model:'EV6',                year:2026, trim:'Long Range AWD',    class:'Mid-size Car',     body_style:'Car',   engine_litres:null,cylinders:0, motor_kw:239,  transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:499, ev_range_cold_km:299, co2_rating:10, smog_rating:10, msrp_cad:65995,  ground_clearance_mm:160, kwh_per_100km:17.5 },
    { id:46, make:'Tesla',      model:'Model Y',            year:2026, trim:'RWD',               class:'Mid-size SUV',     body_style:'SUV',   engine_litres:null,cylinders:0, motor_kw:220,  transmission:'1-spd Auto',   drivetrain:'RWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:533, ev_range_cold_km:320, co2_rating:10, smog_rating:10, msrp_cad:59990,  ground_clearance_mm:167, kwh_per_100km:17.0 },
    { id:47, make:'Ford',       model:'Mustang Mach-E',     year:2026, trim:'Select AWD',        class:'Mid-size SUV',     body_style:'SUV',   engine_litres:null,cylinders:0, motor_kw:258,  transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:490, ev_range_cold_km:294, co2_rating:10, smog_rating:10, msrp_cad:66995,  ground_clearance_mm:148, kwh_per_100km:21.5 },
    { id:48, make:'Volkswagen', model:'Jetta',              year:2026, trim:'Comfortline',       class:'Compact Car',      body_style:'Car',   engine_litres:1.5, cylinders:4, motor_kw:null, transmission:'8-spd Auto',   drivetrain:'FWD', fuel_type:'gasoline', fuel_city_l100km:7.4,  fuel_hwy_l100km:6.5,  fuel_combined_l100km:7.0,  ev_range_km:null, ev_range_cold_km:null, co2_rating:5,  smog_rating:5,  msrp_cad:27995,  ground_clearance_mm:127 },
    { id:49, make:'Honda',      model:'Accord Hybrid',      year:2026, trim:'EX-L',              class:'Mid-size Car',     body_style:'Car',   engine_litres:2.0, cylinders:4, motor_kw:135,  transmission:'eCVT',         drivetrain:'FWD', fuel_type:'hybrid',   fuel_city_l100km:5.3,  fuel_hwy_l100km:6.2,  fuel_combined_l100km:5.7,  ev_range_km:null, ev_range_cold_km:null, co2_rating:4,  smog_rating:7,  msrp_cad:42290,  ground_clearance_mm:140 },
    { id:50, make:'Rivian',     model:'R1T',                year:2026, trim:'Adventure AWD',     class:'Full-size Pickup', body_style:'Truck', engine_litres:null,cylinders:0, motor_kw:522,  transmission:'1-spd Auto',   drivetrain:'AWD', fuel_type:'BEV',      fuel_city_l100km:null, fuel_hwy_l100km:null, fuel_combined_l100km:null, ev_range_km:563, ev_range_cold_km:338, co2_rating:10, smog_rating:10, msrp_cad:109900, ground_clearance_mm:278, kwh_per_100km:28.0 },
    { id:51, make:'Jeep',       model:'Wrangler 4xe',       year:2026, trim:'Rubicon PHEV',      class:'Mid-size SUV',     body_style:'SUV',   engine_litres:2.0, cylinders:4, motor_kw:90,   transmission:'8-spd Auto',   drivetrain:'4WD', fuel_type:'PHEV',     fuel_city_l100km:3.7,  fuel_hwy_l100km:10.2, fuel_combined_l100km:7.1,  ev_range_km:40,  ev_range_cold_km:24,  co2_rating:4,  smog_rating:4,  msrp_cad:73445,  ground_clearance_mm:252 },
    { id:52, make:'Ford',       model:'Maverick Hybrid',    year:2026, trim:'XLT FWD',           class:'Mid-size Pickup',  body_style:'Truck', engine_litres:2.5, cylinders:4, motor_kw:null, transmission:'CVT',          drivetrain:'FWD', fuel_type:'hybrid',   fuel_city_l100km:7.0,  fuel_hwy_l100km:7.8,  fuel_combined_l100km:7.4,  ev_range_km:null, ev_range_cold_km:null, co2_rating:5,  smog_rating:6,  msrp_cad:37500,  ground_clearance_mm:202 },
  ];

  // Enrich: ensure ev_range_cold_km is populated for BEV/PHEV using CAA -20°C formula
  const vehicles = RAW_VEHICLES.map(v => {
    const enriched = Object.assign({}, v);
    if ((enriched.fuel_type === 'BEV' || enriched.fuel_type === 'PHEV') &&
        enriched.ev_range_km && !enriched.ev_range_cold_km) {
      enriched.ev_range_cold_km = Math.round(enriched.ev_range_km * 0.60);
    }
    // Add data_source and data_url
    enriched.data_source = 'NRCan 2026 Fuel Consumption Guide';
    enriched.data_url    = 'https://vehicles.gc.ca';
    return enriched;
  });

  function unique(arr) {
    return [...new Set(arr)].filter(Boolean).sort();
  }

  const makes       = unique(vehicles.map(v => v.make));
  const bodyStyles  = unique(vehicles.map(v => v.body_style));
  const fuelTypes   = ['gasoline', 'diesel', 'hybrid', 'PHEV', 'BEV'];
  const drivetrains = unique(vehicles.map(v => v.drivetrain));

  const msrpValues = vehicles.map(v => v.msrp_cad);
  const minMsrp = Math.min(...msrpValues);
  const maxMsrp = Math.max(...msrpValues);

  return { vehicles, makes, bodyStyles, fuelTypes, drivetrains, minMsrp, maxMsrp };
})();
